# Generated by Django 5.1.4 on 2025-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_book_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
