# Generated by Django 5.1.3 on 2025-03-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_textbook_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='audio_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
